trigger:
  - master

pool:
  name: 'Default' # Specify the name of your agent pool here
  vmImage: 'Default' # Use an appropriate agent here

steps:

- script: |
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -data "$(Build.SourceDirectory)\workspace" -import "C:\Users\lribaya\parasoft\soavirt_workspace_20232\TestAssets"
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -data "$(Build.SourceDirectory)\workspace" -config "soatest.user://Example Configuration" -report "$(System.DefaultWorkingDirectory)"

  displayName: 'Execute soatestcli'

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml


