trigger:
  - master

pool:
  name: 'Default' # Specify the name of your agent pool here
  vmImage: 'Default' # Use an appropriate agent here

steps:

- script: |
    # Commands to execute your executable file
    # Example: ./path/to/your/executable.exe
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -version
  displayName: 'Execute Executable'
    

