trigger:
  - master

pool:
  name: 'Default' # Specify the name of your agent pool here
  vmImage: 'Default' # Use an appropriate agent here

steps:

- script: |
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -data "C:\Users\lribaya\parasoft\soavirt_workspace_20231" -config "soatest.user://Example Configuration"
  displayName: 'Execute soatestcli'


