trigger:
  - master

pool:
  vmImage: 'Default' # Use an appropriate agent here

steps:
- task: DownloadPipelineArtifact@2 # If you want to use artifacts from a previous stage
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    targetPath: '$(System.ArtifactsDirectory)'

- script: |
    # Commands to execute your executable file
    # Example: ./path/to/your/executable.exe
    C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe -version
  displayName: 'Execute Executable'
    

