trigger:
  - master

pool:
  name: 'Default' # Specify the name of your agent pool here


steps:

- checkout: self

- script: |
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -import "C:\Users\lribaya\parasoft\soavirt_workspace_20232\TestAssets" -data "$(Build.SourceDirectory)\workspace"
    "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.2\soatestcli.exe" -data "$(Build.SourceDirectory)\workspace" -config "soatest.user://Example Configuration" -report "$(System.DefaultWorkingDirectory)"

  displayName: 'Execute soatestcli'

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml


